### ISSUE TITLE
user-error "Method ‘yadm’ is not known."

### ISSUE THREAD

**Issue by kiaraly** [seanfarley/tramp-yadm#1]
Installed the package for Doom Emacs. However after adding yadm to the projectile projects I get the following error trying to switch projects

`Error in post-command-hook (vertico--exhibit): (user-error "Method ‘yadm’ is not known.")`

This is what my `use-package!` looks like (taken from [https://github.com/elken/doom#tramp-yadm](https://github.com/elken/doom#tramp-yadm))
```elisp
(use-package! tramp-yadm
  :defer t
  :init
  (defun yadm-status ()
    "Invoke magit on the yadm repo"
    (interactive)
    ;(magit-status "/yadm::~")
    (magit-status-setup-buffer "/yadm::~")
    (setq-local magit-git-executable (executable-find "yadm"))
    (setq-local magit-remote-git-executable (executable-find "yadm")))
  (map! :leader :desc "Open yadm status" "g p" #'yadm-status)
  (after! magit
    (tramp-yadm-register)))

```
Error goes away after calling `yadm-status` manually so I assume something isn't being loaded correctly, but I don't know enough about Emacs/Lisp to figure it out myself.

**Comment by seanfarley** [comment]
Usually, that means `tramp-yadm` isn't loading soon enough. Looks like `vertico` is loading (probably with projectile) before `magit` (therefore `tramp-yadm` as well). This is what I have in my doom init:

```emacs-lisp
(use-package! tramp-yadm
  :after (tramp projectile)
  :config
  (setq +vc-gutter-in-remote-files t)
  :init
  (tramp-yadm-register))
```

The `(setq +vc-gutter-in-remote-files t)` is not implemented completely yet, so you can leave it out. You (and elken) shouldn't need anything else (hopefully). Ah! I need to update the readme, so I'll do that now.

**Comment by kiaraly** [comment]
Works without errors now, thanks for the help!

**Comment by kiaraly** [comment]
Just a small follow up: to still keep the behavior of opening magit yadm directly with a keybind I modified the code as follows

```elisp
(defun yadm-status ()
  "Invoke magit on the yadm repo"
  (interactive)
  (require 'tramp-yadm)
  (magit-status-setup-buffer "/yadm::~")
  (setq-local magit-git-executable (executable-find "yadm"))
  (setq-local magit-remote-git-executable (executable-find "yadm")))

(map! :leader :desc "Open yadm status" "g p" #'yadm-status)

(use-package! tramp-yadm
  :after (tramp projectile)
  :init
    (tramp-yadm-register))

```

**Comment by seanfarley** [comment]
Ah, great! Personally, I open it as a projectile project so that I can get a list of files and use magit as normal. The only thing not working is projectile-search. I think it's solvable, just need to figure out the right commands to overload.
